### ISSUE TITLE
[Bug Report] after upgrade to 2.0.0 build is broken

### ISSUE THREAD

**Issue by lhein** [devlato/async-wait-until#7]
In our project we had a PR created today for a version bump from 1.2.6 to 2.0.0. The build for the PR is broken and I am a out of ideas what could cause it. 

See https://github.com/redhat-developer/vscode-didact/pull/420 for the PR created by dependabot.

The build fails with the following error:
```
> vscode-didact@0.3.2 compile /home/circleci/vscode-didact
> tsc -p ./

src/test/suite/didact.test.ts:30:28 - error TS7016: Could not find a declaration file for module 'async-wait-until'. '/home/circleci/vscode-didact/node_modules/async-wait-until/dist/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/async-wait-until` if it exists or add a new declaration (.d.ts) file containing `declare module 'async-wait-until';`

30 import waitUntil = require('async-wait-until');
                              ~~~~~~~~~~~~~~~~~~


Found 1 error.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! vscode-didact@0.3.2 compile: `tsc -p ./`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the vscode-didact@0.3.2 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2021-02-17T08_06_24_845Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! vscode-didact@0.3.2 vscode:prepublish: `npm run clean && npm run compile`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the vscode-didact@0.3.2 vscode:prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2021-02-17T08_06_25_008Z-debug.log

```

Is that a problem with the 2.0.0 version?

**Comment by devlato** [comment]
@lhein Thanks for reporting!
Could you try this, please?
```ts
import { waitUntil } from ('async-wait-until');
```

**Comment by devlato** [comment]
@lhein the issue's fixed, please upgrade to `2.0.1` 🙂
(turns out I didn't update the `files` in `package.json` before publishing `2.0.0`)

**Comment by lhein** [comment]
Thanks for fixing the issue, @devlato.

**Comment by devlato** [comment]
@lhein No worries!
